[project]
authors = ["Alex Nagorny <alex@swaygang.com>"]
entry = "main.sw"
license = "Apache-2.0"
name = "token"

[dependencies]
sway_libs = { git = "https://github.com/FuelLabs/sway-libs", tag = "v0.22.0" }
standards = { git = "https://github.com/FuelLabs/sway-standards", tag = "v0.5.1" }
